CREATE TABLE APP_USERS (
    USER_ID VARCHAR2(30) PRIMARY KEY,
    PASSWORD VARCHAR2(30) NOT NULL
);

INSERT INTO APP_USERS VALUES ('admin', 'admin123');
INSERT INTO APP_USERS VALUES ('staff', 'gas123');
INSERT INTO APP_USERS VALUES ('student','student123');

COMMIT;


